### ISSUE TITLE
Move the stream handler outside of the main file (into its own .hpp file)

### ISSUE THREAD

**Issue by erichkeane** [erichkeane/const_expr_string#1]
The stream handling will make the main include require inclusion of some of the stream headers, so it should be separated out into its own header.

**Comment by whoshuu** [comment]
I think you've addressed this issue already. If not, could you clarify what else you mean to separate into its own header?

**Comment by erichkeane** [comment]
I haven't done this one yet.  Basically, the idea is to pull the ostream overload into its own header file that requires explicit including, so that people just using the library don't get stuck with bringing in the entire iostream/stringstream library into their build.

**Comment by whoshuu** [comment]
Gotcha. Thanks for clarifying, I understand what you're saying now.

I actually think the way things are set up now, you don't need to do anything else. For someone to use the ostream overload, they'll need a `stringstream` or `ostream`. You _want_ someone to have to explicitly include the header themselves outside of what you're providing in your own headers, and they'll do this naturally because they need a `stringstream` or `ostream` object themselves (to throw your string_view into).

Since the ostream overload is templated, it won't get stamped out until someone tries to use it. Someone attempting to use it will have a stream of some sort. If they have a stream, then they should be forced to include the appropriate stream header independently of your header.

**Comment by whoshuu** [comment]
Case in point, `main.cpp` includes stream headers on its own. If we assume that all `main.cpp` did was test the ostream overload, it won't compile if it doesn't include those headers, even if it includes every header you provide. And it would make sense to the user of your library that it won't compile because duh, they're instantiating a stream of some sort without including the appropriate header.

**Comment by erichkeane** [comment]
That makes sense.  I haven't tried this from a version that does NOT include, but assuming that it still works (and the compiler doesn't try to check-types anyway), I'm all for closing this one.
